spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plan2go
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
