spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plan2go
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET::change-me-super-long-and-random-32chars-min}
  ttlMinutes: 60